name: Go

on:
  push:
  pull_request:

jobs:

  test:
    strategy:
      matrix:
        go_version: [ 1.16, 1.17 ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Test
        run: go test -v ./...

  build:
    needs:
      - test
    strategy:
      matrix:
        go_version: [ 1.16, 1.17 ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: |
          go build -o jt-${{ matrix.os }} ./cmd/jt

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./jt-${{ matrix.os }}
